import { Extension } from '../src/types';
import { 
  githubConnector, 
  linearConnector, 
  cqConnector, 
  huggingFaceConnector, 
  gmailConnector, 
  slackConnector,
  x402Connector,
  trustpilotConnector,
  arduinoConnector,
  flowiseConnector,
  substackConnector,
  lumaUni1Connector,
  cloudflareCfBridgeConnector,
  frameworkAdapterBridgeConnector,
  linguisticBridgeConnector,
  quantumOpsBridgeConnector,
  sovereignAcademyBridgeConnector,
  sovereignAgentForgeConnector,
  sovereignInteractionSubstrateConnector,
  sovereignPaymentShieldConnector,
  sovereignPulseFeedConnector,
  sovereignSocialSandboxConnector,
  sovereignThreatIntelConnector,
  workspaceBridgeConnector,
  sovereignNewsBridgeConnector,
  sovereignSupplyChainShieldConnector,
  sovereignMcpShieldConnector,
  sovereignMeshConnector
} from './connectors';
import { globalPulseSkill, docForgeSkill, artifactSandboxSkill, codeHunterSkill, socialSentinelSkill, githubSecurityAuditorSkill, creativeDirectorSkill } from './skills';
import { headlessBrowserTool, pdfExtractorTool, codeParserTool } from './tools';
import { localDatabaseMcp, systemMetricsMcp, geminiApiDocsMcp, googleWorkspaceMcp, openClawProtocol } from './mcp';
import { 
  agentTerminalModule, 
  systemMetricsModule, 
  simulationEngineModule, 
  governanceToolkitModule, 
  vibeForgeModule, 
  agentCliModule, 
  sentinelGuardianModule,
  sovereignCreativeStudioModule,
  viabhronNexusModule,
  symphonyModule,
  soundForgeModule,
  imageStudioModule,
  videoSuiteModule,
  mossSystemModule,
  identity8004Module,
  securityRadarModule,
  agentRegistryModule,
  smonitorProtocolModule,
  linguisticBridgeModule,
  memoryPalaceModule,
  verificationLoopModule,
  eventBusModule,
  dispatchModule,
  deepExecutionModule,
  ethicalSentinelModule,
  webReconShieldModule,
  vibeAssemblyModule,
  metabolicSecretaryModule,
  workspaceBridgeModule,
  ambientSounderModule,
  cloudflareBridgeModule,
  socialSandboxModule,
  agentForgeModule,
  frameworkAdapterModule,
  paymentShieldModule,
  threatIntelModule,
  pulseFeedModule,
  academyBridgeModule,
  interactionSubstrateModule,
  seedForgeModule,
  newsBridgeModule,
  supplyChainShieldModule,
  mcpShieldModule
} from './modules';
import {
  cloudManagerAgent,
  fiscalComptrollerAgent,
  identityRegistrarAgent,
  sentinelAgent,
  adversarialAuditorAgent,
  swarmArchitectAgent,
  linguisticEngineerAgent,
  chiefEditorAgent,
  soundEngineerAgent,
  visualSynthesizerAgent,
  nexusLibrarianAgent,
  diplomatAgent,
  metabolicSecretaryAgent
} from './agents';

export const INITIAL_EXTENSIONS: Extension[] = [
  // Connectors
  githubConnector,
  linearConnector,
  cqConnector,
  huggingFaceConnector,
  gmailConnector,
  slackConnector,
  x402Connector,
  trustpilotConnector,
  arduinoConnector,
  flowiseConnector,
  substackConnector,
  lumaUni1Connector,
  cloudflareCfBridgeConnector,
  frameworkAdapterBridgeConnector,
  linguisticBridgeConnector,
  quantumOpsBridgeConnector,
  sovereignAcademyBridgeConnector,
  sovereignAgentForgeConnector,
  sovereignInteractionSubstrateConnector,
  sovereignPaymentShieldConnector,
  sovereignPulseFeedConnector,
  sovereignSocialSandboxConnector,
  sovereignThreatIntelConnector,
  workspaceBridgeConnector,
  sovereignNewsBridgeConnector,
  sovereignSupplyChainShieldConnector,
  sovereignMcpShieldConnector,
  sovereignMeshConnector,
  
  // Skills
  globalPulseSkill,
  docForgeSkill,
  artifactSandboxSkill,
  codeHunterSkill,
  socialSentinelSkill,
  githubSecurityAuditorSkill,
  creativeDirectorSkill,
  
  // Tools
  headlessBrowserTool,
  pdfExtractorTool,
  codeParserTool,

  // MCP Servers
  localDatabaseMcp,
  systemMetricsMcp,
  geminiApiDocsMcp,
  googleWorkspaceMcp,
  openClawProtocol,

  // Modules
  agentTerminalModule,
  systemMetricsModule,
  simulationEngineModule,
  governanceToolkitModule,
  vibeForgeModule,
  agentCliModule,
  sentinelGuardianModule,
  sovereignCreativeStudioModule,
  viabhronNexusModule,
  symphonyModule,
  soundForgeModule,
  imageStudioModule,
  videoSuiteModule,
  mossSystemModule,
  identity8004Module,
  securityRadarModule,
  agentRegistryModule,
  smonitorProtocolModule,
  linguisticBridgeModule,
  memoryPalaceModule,
  verificationLoopModule,
  eventBusModule,
  dispatchModule,
  deepExecutionModule,
  ethicalSentinelModule,
  webReconShieldModule,
  vibeAssemblyModule,
  metabolicSecretaryModule,
  workspaceBridgeModule,
  ambientSounderModule,
  cloudflareBridgeModule,
  socialSandboxModule,
  agentForgeModule,
  frameworkAdapterModule,
  paymentShieldModule,
  threatIntelModule,
  pulseFeedModule,
  academyBridgeModule,
  interactionSubstrateModule,
  seedForgeModule,
  newsBridgeModule,
  supplyChainShieldModule,
  mcpShieldModule,

  // Agents
  cloudManagerAgent,
  fiscalComptrollerAgent,
  identityRegistrarAgent,
  sentinelAgent,
  adversarialAuditorAgent,
  swarmArchitectAgent,
  linguisticEngineerAgent,
  chiefEditorAgent,
  soundEngineerAgent,
  visualSynthesizerAgent,
  nexusLibrarianAgent,
  diplomatAgent,
  metabolicSecretaryAgent,
];
